version: "3.7"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: incredible_local_secret_phrase
      POSTGRES_USER: postgres
    healthcheck:
      test: "pg_isready --username=postgres"
      timeout: 10s
      retries: 20
    init: true
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  remix_dev:
    build:
      target: dev
      context: .
    depends_on:
      postgres:
        condition: service_healthy
      s3-local:
        condition: service_started
      createbuckets:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: postgresql://postgres:incredible_local_secret_phrase@postgres:5432/postgres?schema=public
      S3_ENDPOINT_URL: http://s3-local:9000
      AWS_ACCESS_KEY_ID: "e2e_minio"
      AWS_SECRET_ACCESS_KEY: "incredible_local_secret_phrase"
      MAX_UPLOAD_FILECOUNT: 5
      MAX_UPLOAD_SIZE_BYTES: 5242880
      LOG_LEVEL: debug
      PUBLIC_DEMO_MODE: true
    init: true
    ports:
      - "3003:3000"
      - "6066:6006"
      - "8002:8002"
    volumes:
      # Mount the app directory for faster local development.
      - ./:/home/node/remix
      # Use a named volume for the node_modules so that the container uses the guest machine's node_modules dir instead of the host machine's node_modules directory, which might be divergent.
      - remix_dev_nodemodules:/home/node/remix/node_modules

  remix_prod:
    build:
      target: prod
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:incredible_local_secret_phrase@postgres:5432/postgres?schema=public
      S3_ENDPOINT_URL: http://s3-local:9000
      AWS_ACCESS_KEY_ID: "e2e_minio"
      AWS_SECRET_ACCESS_KEY: "incredible_local_secret_phrase"
      LOG_LEVEL: warn
      PUBLIC_DEMO_MODE: true
    init: true
    ports:
      - "3010:3000"
    read_only: true
    volumes:
      - remix_prod_tmp:/tmp

  s3-local:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: e2e_minio
      MINIO_ROOT_PASSWORD: incredible_local_secret_phrase
    command: server --console-address ":9001" /data

  createbuckets:
    image: minio/mc
    depends_on:
      - s3-local
    entrypoint: >
      /bin/sh -c "/usr/bin/mc config host add myminio http://s3-local:9000 e2e_minio incredible_local_secret_phrase; /usr/bin/mc mb myminio/participant-uploads; exit 0; "

volumes:
  remix_dev_nodemodules:
  remix_prod_tmp:
  postgres_data:
  minio_storage:
